import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Layout({ children }) {
    return (
        <div className={'h-100 w-100'}>
            <Head>
                <meta charSet="utf-8"></meta>
                <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>{children}</main>

            <footer></footer>
        </div>
    );
}
